### ISSUE TITLE
Retain place in lists when switching views

### ISSUE THREAD

**Issue by gilgilliam** [ledgerleapllc/devxdao-backend#106]
Hi. Can we enable the All Proposals page  (and any pages where we can go from list to detail back to list) to retain memory of where a user is in the list when they click away to a specific grant and then return to list page? Very tedious to have to scroll down from most recent grant every tine when trying to look at very early grants.

**Comment by ledgerleapllc** [comment]
GP-473

**Comment by ledgerleapllc** [comment]
Deployed
