### ISSUE TITLE
[BUG] Proposal 493 doesn't show any milestone

### ISSUE THREAD

**Issue by KillianH** [ledgerleapllc/devxdao-backend#110]
The proposal https://portal.devxdao.com/app/proposal/493 doesn't show any milestone.

The API return an empty array and no error are displayed in the devtool console on the frontend.

**Comment by ledgerleapllc** [comment]
It appears that this proposal was submitted using Postman or something. Frontend wont allow a submission without at least one milestone. We could start this one over and resubmit properly to fix this issue.
