### ISSUE TITLE
Upgrades to staking system and REP distribution points

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#113]
We propose a change to the Reputation system concerning the releasing of REP minted through grants and REP used to vote.Currently, the system processes REP unlocks and locks the following ways in respect to grant applicants and VAs voting on grants -• Grant applicants receive “minted pending” REP based on the Euro value of their grant when the grant is approved. This minted pending REP only converts to available REP when the final milestone is complete for the grant.The issue is that applicants cannot fully engage with the ecosystem (using REP) until their grants are entirely complete, which can take extended periods of time for larger grants. This decreases engagement from new VAs and does not optimize the timely distribution of REP.• VAs voting on grants “stake” their REP towards a formal vote. If this formal vote passes, they receive a pro-rata portion of the total minted pending REP from the “policing ratio” as calculated by the number of REP points they voted with compared to the total REP points of all VAs voting. The VA then immediately receives the REP staked to the vote back when the vote concludes, along with gaining a line item in the minted pending column of their REP chart as a portion of the grant’s REP generated by the “policing ratio.”This causes two issues.• Grant applicants cannot fully engage with the ecosystem (using REP) until their grants are entirely complete, which can take extended periods of time for larger grants. This decreases engagement from new VAs and does not optimize the timely distribution of REP. This is a symptom of departures from the original MVPR system that is described in the cited works of #18; in the cited system, evidence is to be submitted for the completed work alongside the request for payment, thereby eliminating this 'lag time'. However, it is inherently impractical to asking individuals and companies to shoulder the entire burden of development cost. The costs surrounding software development are simply too great, necessitating the departure.• Over time, VAs with larger REP pools as they vote on high-value grants. VAs with large REP pools can vote the maximum allowed - to reserve a large portion of the minted pending REP - as compared to those with smaller REP pools. This can create a widening gap between the REP earned by new VAs versus older VAs based solely on the relatively passive activity of voting. Cycling large amounts of reputation on every vote gives established VAs a large advantage. This is a departure in spirit from the cited works in #18. A core tenet of the MVPR system is that voting associates must literally stake their reputation in proportion to the strength of their opinion on the subject at hand. At current, this is functionally not done as the REP is returned before the result of the subject at hand is known.We resolve a solution to both issues.Resolved:

Grant applicants are to have portions of their REP unlocked as they complete milestones. For example, if a grant totals 100K EUR and the applicant completes the first milestone with a value of 20K EUR, the system would unlock 20% of the applicant’s minted pending REP by shifting it to available status. This is functionally already done by the resolution in #141; this merely formalizes and mandates the mechanization of the practice.• For the VA group, REP staked to a formal vote is to no longer return to available status when the vote completes. Rather, it shall remain locked pending the completion of the grant itself, unlocking in portions with each milestone. For example, if a VA stakes 100 REP in a formal vote, this vote passes, and a 100K EUR proposal becomes a grant, then this VA will have their 100 REP remain locked. As the grant’s first milestone passes with a 20K EUR value, the system shall unlock 20% of the VA’s staked REP from the vote, in addition to any REP they earn from the policing ratio.The intended net effect of these changes is to provide more balance and opportunity in the ecosystem. Incoming VAs must have access to more of their minted pending REP, and must be provided with opportunities with which to use it to their own greatest benefit.The mechanization of this process is nontrivially difficult. Specifically, It is difficult to precisely predict the amount of time required to make these changes; however, the OP shall, upon the pass of this resolution, allocate two senior developers and one product manager to rewiring this core part of the system. The OP estimates three days for each change to the reputation management and disbursement system (6 days total) and require one week following of testing time on the staging servers. Testing will consist of running a batch of new VA’s through rapid sample grants and checking REP allocations manually against offline systems such as excel spreadsheets running the same formulas. Test scripts will need to also be built. Once tested, we will merge these new features into the existing portal. Testing is critical for these updates as REP is foundational to the entire DxD system

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/issues/69

**Comment by ledgerleapllc** [comment]
jira 457

**Comment by opticalresolution** [comment]
^^^ 
***Proposal Number in the DxD 457
Jira GP-429

**Comment by opticalresolution** [comment]
https://github.com/ledgerleapllc/devxdao-backend/issues/97
