### ISSUE TITLE
2 updates to UX

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#127]
See attached PDF

• We are adding the ability to see total of an OPs grants (not admin) publicly

• We are adding the ability to filter out attestations already made.
[Updates Mar24th.pdf](https://github.com/ledgerleapllc/devxdao-backend/files/8344473/Updates.Mar24th.pdf)

gp472

**Comment by ledgerleapllc** [comment]
Closed on frontend

**Comment by ledgerleapllc** [comment]
Extra commit: https://github.com/ledgerleapllc/devxdao-backend/commit/911e52d98760c53a6c8db37d12f95b1a4cf22c4b
