### ISSUE TITLE
Add grant total to this table

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#128]
In admin user detail page, we need grant total added as a column
![image](https://user-images.githubusercontent.com/93783672/159987936-b4859992-bc8a-40d6-973f-e6ce580d6542.png)

gp471

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/pull/122
https://github.com/ledgerleapllc/devxdao-backend/pull/126

**Comment by opticalresolution** [comment]
Tested and on production
