### ISSUE TITLE
Grant #451 requires manual activation

### ISSUE THREAD

**Issue by tmesser** [ledgerleapllc/devxdao-backend#131]
Grant #451 had a hiccup with HelloSign and needs manual activation in the portal. I will link the completed grant form in the appropriate Telegram channel - I'm reluctant to link it in this topic.

**Comment by opticalresolution** [comment]
Yes please do not link it here but rather send it to me (Sam) privately.

**Comment by tmesser** [comment]
Just to follow up, I linked it in the telegram channel shortly after I posted this issue. Please reach out on telegram if you still do note see it @opticalresolution.

**Comment by opticalresolution** [comment]
Manually uploaded the grant agreement and activated the grant.
