### ISSUE TITLE
REQUEST: Change color of Program Management Approval button based on action to be taken

### ISSUE THREAD

**Issue by tmesser** [ledgerleapllc/devxdao-backend#132]
CURRENT:
There is a 'Submit Review' button at the bottom of the checklists surrounding a milestone's review (URL: https://pm.devxdao.com/app/assign/###). It is unclickable while one of the checkboxes in the above checklists are not filled out, and becomes a deep purple, and clickable when the review is complete.

DESIRED:
Instead of a deep purple, the button should turn green if submitting the review will result in an acceptance of the milestone and a send to the DEVxDAO for vote, or red if submitting the review will result in the failure of the milestone and the OP being emailed.

**Comment by opticalresolution** [comment]
GP-475

**Comment by opticalresolution** [comment]
Feature tested well on staging environment. Pushed to production

**Comment by ledgerleapllc** [comment]
PM portal commit: https://github.com/ledgerleapllc/devxdao-pm/commit/bf563f482125d344f980523c49fc6655047158f7
