### ISSUE TITLE
We can't see who has and hasn't attested.

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#140]
Portal needs a screen to view this info.

**Comment by ledgerleapllc** [comment]
GP 478

**Comment by mrkara** [comment]
Hi @ledgerleapllc!  Is there any info about who requested this feature, when, where, and why? Might be good to have them on record for teh future, and also for the purpose of assessing importance/priority.

**Comment by ledgerleapllc** [comment]
Deployed. We are not billing for this one @mrkara but it needs to exist. Sometimes we eat costs on these for efficiency because we identify a problem, they are small, and no VA prompts it for fix. The why is because things remain in attestation for long periods and Tim M has not oversight into who he needs to speak to to move things.
