### ISSUE TITLE
Admin Reputation Functions

### ISSUE THREAD

**Issue by josh-bykowski** [ledgerleapllc/devxdao-backend#142]
- Simple Vote 520 required a deduction of 300 rep from founders. 
- However, the Admin rep function for changing a user's REP score only includes REP that is "Available" (or unstaked). 
- This resulted in a specific issue for Wulf because he was a founding VA who only had 214 REP "Available" - the other 713 is staked.
- The system does not allow a negative REP number, which prevents Wulf's necessary -300 REP deduction. 
- The first image is Wulf's total REP distribution. 
- The second image shows what Admin sees when attempting to alter Wulf's REP. 
- Let me know if there are any questions
![wulfrepissue2](https://user-images.githubusercontent.com/101903577/161332805-2fb13f51-0c34-42a5-a6f1-780e1855cc31.JPG)

If the system 
![wulfrepissue](https://user-images.githubusercontent.com/101903577/161331970-85404b79-2571-432f-a436-7f2f34e8f914.JPG)

**Comment by ledgerleapllc** [comment]
Checking in with this ticket item. Looks like this is mostly resolved. Are we still waiting to execute a -300 request on individuals that were under 300 at the time of the admin action?
