### ISSUE TITLE
Multi milestone issue

### ISSUE THREAD

**Issue by timothytlewis** [ledgerleapllc/devxdao-backend#151]
Repeating issue when voting on multimilestone votes. 

I am unable to vote on multiple informal items when presented in the system.

 ![image](https://user-images.githubusercontent.com/6579135/161612320-bb553d23-77a4-4aec-b7d0-5eea86bf6d8c.jpeg)![image](https://user-images.githubusercontent.com/6579135/161612373-461df146-7822-4e95-a1d5-fe150d61fd8b.jpeg)![image](https://user-images.githubusercontent.com/6579135/161612401-a9b3a0ac-b9d4-45b3-a2ea-bef809382a9c.jpeg)

This is one example from the month of March. I will get a screen share going next time there is a multi milestone vote going.

**Comment by ledgerleapllc** [comment]
Our team cannot replicate after 2 hours devoted to task and we have no other reports. 

Next step planned - @timothytlewis  to reach out to Sam to have a zoom the next time multi-milestone vote is active. This process to be done from a computer using chrome. A recorded screenshare will watch the potential error and devtools will be open to view logs/errors.

**Comment by opticalresolution** [comment]
Same issue: https://github.com/ledgerleapllc/devxdao-backend/issues/69
