### ISSUE TITLE
Attestation is not locked to time of attestation

### ISSUE THREAD

**Issue by davidtai** [ledgerleapllc/devxdao-backend#155]
![image](https://user-images.githubusercontent.com/8346495/162047942-0483b29b-b81c-4d0c-847e-cf30139595ca.png)

Attestation current changes with new users being onboarded.  It should retain the attestation rate using the number of VA at the time it was put into vote.

**Comment by ledgerleapllc** [comment]
GP486

**Comment by ledgerleapllc** [comment]
Locking the VA count at the time when attestation begins. Need a new database column for this
