### ISSUE TITLE
Users unable to vote on certain milestones

### ISSUE THREAD

**Issue by tmesser** [ledgerleapllc/devxdao-backend#164]
EXPECTED:
VAs should be able to vote on all milestones in informal voting.

ACTUAL:
Forum name `sergio [Nodes.Guru]` can vote on milestone 1 for Proposal #235 (currently in vote), but not milestone 1 for Proposal #342 (also currently in vote)

![image](https://user-images.githubusercontent.com/1832023/163313748-7826d83d-9d0e-4bda-a1e9-1ddd0d2941e7.png)
![image](https://user-images.githubusercontent.com/1832023/163313759-4a845b1b-f527-469c-8788-df77e61278e3.png)

**Comment by tmesser** [comment]
Disregard. As we figured out, the user had already voted for #342 and was confused regarding feedback. We can make a note of this for future improvements, but low priority.

**Comment by opticalresolution** [comment]
Thanks @tmesser
