### ISSUE TITLE
PM process needs looking at, not storing details correctly (Reporter: Tim Messer)

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#165]

**Comment by ledgerleapllc** [comment]
GP 501

**Comment by tmesser** [comment]
Correct, I did report this.

Background: I asked for a small change to force the submit button on my project management portal to turn GREEN if I was about to pass the milestone into voting, and RED if I was about to reject it. There have been a few instances where I have clicked a green button and rejected the milestone. When I go back to look at the milestone, it's X'd out a random box.

An example of this is in #246, milestone 3, submission 1. The question "Expert DAO (CR DAO) has accepted program management T&C" is X'd out, which makes no sense whatsoever for me to do.

**Comment by ledgerleapllc** [comment]
commit: https://github.com/ledgerleapllc/devxdao-pm/commit/051340b7068e8540a37a3fa91b81bf72fd902ea8
PR: https://github.com/ledgerleapllc/devxdao-pm/pull/5
PR: https://github.com/ledgerleapllc/devxdao-pm/pull/6

**Comment by ledgerleapllc** [comment]
![issue-165](https://user-images.githubusercontent.com/69469839/167164585-6e88aa73-0568-4788-b91c-6a6337c27a05.png)

**Comment by opticalresolution** [comment]
New GP-509

**Comment by opticalresolution** [comment]
this was form validation issue, even all fields are not checked, form was validated and submit button went green
