### ISSUE TITLE
Bug when adding/removing attachments from proposals in discussions phase 

### ISSUE THREAD

**Issue by dlndao** [ledgerleapllc/devxdao-backend#166]
If a file is uploaded and then newer versions are added, the system will show all the versions on submission.
![Screen Shot 2022-04-21 at 12 04 16 PM](https://user-images.githubusercontent.com/73374148/164513452-ffa1c661-d65f-4d48-bdf3-4aea0b88489f.png)

**Comment by opticalresolution** [comment]
Having trouble replicating this @dlndao 

I created a proposal, added 4 files, then removed 4 of the 2. After submitting it, only the correct 2 files show. If I click on edit proposal, I can add or take files away. When I click save, the new files are saved. 

Please, in detail, let me know exactly how I can replicate this issue.

**Comment by opticalresolution** [comment]
gp-501

**Comment by opticalresolution** [comment]
A fix was written and pushed to the testing environment. Tested the issue and it is now working correctly.

**Comment by ledgerleapllc** [comment]
@opticalresolution I believe there is a typo above. gp-502 is the jira number I'm reading for this issue.

**Comment by ledgerleapllc** [comment]
Backend commit: https://github.com/ledgerleapllc/devxdao-backend/commit/e2dc7a5cb47db84618c569dcce2a1d3f9f0142ca
All good.
