### ISSUE TITLE
Bug - OP proposal withdrawal process at various proposal stages is not configured to handle REP returns.

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#169]
Adding feature to fix GP 503

**Comment by opticalresolution** [comment]
We need to add logic that returns staked REP to an OP if they withdraw their own proposal. 

We also need to make a command that checks if any users are affected. Check if any proposals were withdrawn by user, and then see how much they staked, and see if it came back or not.

**Comment by opticalresolution** [comment]
The issue has been resolved.
