### ISSUE TITLE
Error on /topics and /discussions details (you are not permitted)

### ISSUE THREAD

**Issue by caspercommunityio** [ledgerleapllc/devxdao-backend#179]
The problem occurs since 27/04/2022 (or 28/04/2022)

The /topics page is empty :
![image](https://user-images.githubusercontent.com/91611216/165824894-671abcb5-b2ee-45f5-8642-ceaa9a17c1be.png)

The /discussions return this message when I click on a detail :
![image](https://user-images.githubusercontent.com/91611216/165825140-79ac22bb-d0f9-4984-b820-ce778060f41e.png)

The inspect from the browser show me the following message for both page:
![image](https://user-images.githubusercontent.com/91611216/165825273-65f70bf3-5b0f-42ac-ad30-6642129c0642.png)

**Comment by dlndao** [comment]
I am getting the same for days now, tried on Chrome, Safari, FF, and Brave.

**Comment by opticalresolution** [comment]
This is an ongoing discourse integration problem. Some time will have to be allocated to get to the root cause and fix. This will keep happening unless we circle back and come up with a different solution.

**Comment by opticalresolution** [comment]
https://github.com/ledgerleapllc/devxdao-backend/issues/159
