### ISSUE TITLE
Attestation column is not updating (Reporter BogosChad)

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#185]
![Screen Shot 2022-05-07 at 10 03 10 AM](https://user-images.githubusercontent.com/69469839/167257709-18faeed5-0698-4128-a191-ee2ead3e4094.png)

**Comment by ledgerleapllc** [comment]
510

**Comment by opticalresolution** [comment]
A fix was released. Should be working properly now. Ready to close this issue
