### ISSUE TITLE
"Provide all the necessary information" error while signing up

### ISSUE THREAD

**Issue by alexxtomsk** [ledgerleapllc/devxdao-backend#187]
I'm trying to signup at https://portal.devxdao.com/register/form but getting the error "Provide all the necessary information". Did a dozen tries with various options, and it still shows the error. Probably something is wrong here.

**Comment by alexxtomsk** [comment]
I tried in Chrome and Mozilla (macos) and got the same result.

**Comment by opticalresolution** [comment]
Ticket opened - 513

**Comment by opticalresolution** [comment]
We checked the registration system out and made small updates to the error handling. Asked the user to try again and it seems to be working now for them. Consider this closed.
