### ISSUE TITLE
Bug in automatically moving to informal vote

### ISSUE THREAD

**Issue by wulfkaal** [ledgerleapllc/devxdao-backend#192]
#541 not moving to voting with 51.29% attestation ? It has been sitting at that level for days

**Comment by ledgerleapllc** [comment]
PR: https://github.com/ledgerleapllc/devxdao-backend/pull/202

**Comment by ledgerleapllc** [comment]
PR: https://github.com/ledgerleapllc/devxdao-backend/pull/193

**Comment by opticalresolution** [comment]
This was caused when the topics title was already used. Wrote logic that will not allow duplicate titles to be used and will throw a front end error message asking the user to change the title if it is already taken.
