### ISSUE TITLE
There is a completed draft proposal that is not able to be submitted (regular grant proposal)

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#195]
Getting the error, "provide all the necessary information" but the form is complete. 

Draft ID: 450

![telegram-cloud-photo-size-4-5818813433854933901-x](https://user-images.githubusercontent.com/93783672/171459881-fee2dfe3-76ac-4d46-9b1b-d069d10c5c52.jpg)

**Comment by ledgerleapllc** [comment]
and 521

**Comment by opticalresolution** [comment]
A fix has been tested and pushed. The issue is now resolved
