### ISSUE TITLE
Proposal 531 not appearing on the "Move to Formal" tab 

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#203]
It should be found in the “Move to Formal” tab - but it’s not there. Showing as "Informal vote finished" 

Also, I have no controls to manually start the formal vote as an admin, when looking at the proposal itself.

**Comment by opticalresolution** [comment]
522

**Comment by KillianH** [comment]
Thx for the issue. The compliance was denied and then accepted a few days after fyi

**Comment by opticalresolution** [comment]
Thanks @KillianH - thats huge! Should have an update for you in the next few hours.

**Comment by KillianH** [comment]
> Thanks @KillianH - thats huge! Should have an update for you in the next few hours. 

Thx 🔥

**Comment by opticalresolution** [comment]
@KillianH proposal has been moved to the "Move to Formal" tab and is ready to start the formal vote. Do we want to start it now?

**Comment by KillianH** [comment]
> @KillianH proposal has been moved to the "Move to Formal" tab and is ready to start the formal vote. Do we want to start it now? 

Yep !

**Comment by opticalresolution** [comment]
Proposal 531 is in formal voting. The manual move from the compliance portal caused it to hang on the DxD side and not appear in the correct tab so unable to start formal voting. We are adding a way for admins to change compliance status from within the compliance portal to prevent this from happening again in the future.
