### ISSUE TITLE
Portal showing wrong status on fail (Reported by Huy Tran)

### ISSUE THREAD

**Issue by ledgerleap** [ledgerleapllc/devxdao-backend#210]

**Comment by ledgerleap** [comment]
![Screen Shot 2022-06-11 at 10 42 15 AM](https://user-images.githubusercontent.com/68660281/173192566-e1e28e68-3d75-449f-9e9b-fb5547973848.png)

**Comment by ledgerleap** [comment]
Reported by Huy Tran

**Comment by opticalresolution** [comment]
This issue has been resolved!
