### ISSUE TITLE
On the votes tab, add a column in both tables for attestation rate. 

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#37]
Add a column for attestation rate % in the votes tab. Add in both tables.
![Screen Shot 2022-02-14 at 2 43 29 PM](https://user-images.githubusercontent.com/93783672/153935384-c0332676-4736-4d91-a836-c910a6599f41.png)

**Comment by opticalresolution** [comment]
@davutkmbr

**Comment by ledgerleapllc** [comment]
Also, quick note. The column headers are "Attestation" and "Have I Attested" on the Discussions ta. Would recommend making both "Attestation" and "Attested" for the column header names. Seems more efficient.

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-frontend/issues/22

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/pull/91
