### ISSUE TITLE
Informal downvotes must still move to Formal - Proposal #428

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#44]
The portal is currently configured to terminate a proposal after an informal Downvote. We need to update this to allow proposals to move into formal voting even if the are downvoted on the informal vote. 

Current Flow: Informal vote → Downvoted → Proposal does not move on. 

New Flow: Informal vote → Downvoted → Proposal adopts same logic as if it passed. Moves forward to Formal vote.

**Comment by ledgerleapllc** [comment]
Waiting for confirmation on assignment

**Comment by opticalresolution** [comment]
In progress

**Comment by ledgerleapllc** [comment]
Jira # 436

**Comment by KillianH** [comment]
To add to the context : only proposal that reach quorum and are failed should move to the formal vote.

**Comment by ledgerleapllc** [comment]
GP436

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/pull/92
