### ISSUE TITLE
Make topics search bar work with numbers 

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#51]
Hey @davutkmbr this is something still on my radar. 

• If I type in the search bar 355 for example, I do not get any results. Should see proposal 355. 

![image](https://user-images.githubusercontent.com/93783672/154152308-7bd72fd8-c182-4f36-9fce-d6d31a635e38.png)

**Comment by ledgerleapllc** [comment]
GP-437
