### ISSUE TITLE
Upload signed agreement to proposal 318

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#55]
Manually add this to 318 and update the portal to reflect all 3 have signed. Still showing 1/3 here:
![image](https://user-images.githubusercontent.com/93783672/154154140-09caf59f-45a2-4b81-b17d-38b93e6194a3.png)

![image](https://user-images.githubusercontent.com/93783672/154154162-d5ea4926-a580-4d9b-beb2-f456a3df58ec.png)

The “activate grant” button should be activated so that an  ADMIN can click it and activate Grant 318.

**Comment by ledgerleapllc** [comment]
Commit https://github.com/ledgerleapllc/devxdao-backend/commit/52aa607dbc9e14b7fe1c9258cd4de73c364899f2
