### ISSUE TITLE
KYC Kangaroo - Backend/front end updates

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#63]
Initial instructions were to have API users completely separate from main dashboard users. This has become a problem so we will be implementing a fix. Currently if user.api_user = devxdao, then they do not show up in main table, but only show up in api user table. 

We will be updating this so that all users, including users from user.api_user, will be included in all regular kyckangaroo admining areas (the dashboard) 

The api_user devxdao should also show up in api users tab as well.

All areas also means they should show up in entity view tables where you can see individuals inside. We need to see api users everywhere where normal users are seen.

So api users tab basically becomes a filtered view of JUST a particular api_user kind. That is its only purpose now

**Comment by ledgerleapllc** [comment]
Updated KYCKangaroo backend to join api_users and normal users so that they can be associated with one another cross platform.
