### ISSUE TITLE
Some users are having issues with voting on multiple milestones. 

### ISSUE THREAD

**Issue by opticalresolution** [ledgerleapllc/devxdao-backend#69]
**Report:**

Timothy Lewis | DEVxDAO | ikigai, [Feb 21, 2022 at 11:48:19 AM]:
There is something wrong with voting on the multiple milestone votes
And it’s unfairly affecting our vote percentages
I am always only able to vote on ONE of the multiples in informal (typically i go bottom up)
And then after one is voted, I can’t vote for others

_____

Based on this information there is a bug thats happening when users try to vote on multiple milestones. 

This started happening when we introduced multiple milestone votes. 

This has been identified for some users on either mobile or tablet. Might also be a problem on desktop but was reported by someone using mobile. 

____

Additional Report: 

"There’s definitely a bug, it says over a three day. I didn’t vote, and missed 9 vote  all in a row…. All milestones except for one."

**Comment by ledgerleapllc** [comment]
Jira ticket #428

**Comment by ledgerleapllc** [comment]
Unable to replicate. No further information received. Closing for now and can re-open if more symptoms come to light.

**Comment by opticalresolution** [comment]
GP-482
