### ISSUE TITLE
[BUG][428] Failed informal vote aren't being push into formal vote

### ISSUE THREAD

**Issue by KillianH** [ledgerleapllc/devxdao-backend#81]
There's a bug on the portal that happen when an informal vote fail (with quorum) when people voted against it the grant/simple vote/admin grant doesn't move into formal vote.

So :
When a informal vote reach quorum it should goes into formal even if the VA's vote against it. **But ONLY if it reach quorum**

Ref : https://portal.devxdao.com/app/proposal/428

**Comment by ledgerleapllc** [comment]
Jira # 436

**Comment by ledgerleapllc** [comment]
This is addressed in https://github.com/ledgerleapllc/devxdao-backend/issues/44
