### ISSUE TITLE
Change to the Reputation system

### ISSUE THREAD

**Issue by ledgerleapllc** [ledgerleapllc/devxdao-backend#97]
We propose a change to the Reputation system concerning the releasing of REP minted through grants and REP used to vote.Currently, the system processes REP unlocks and locks the following ways in respect to grant applicants and VAs voting on grants -

-  Grant applicants receive “minted pending” REP based on the Euro value of their grant when the grant is approved. This minted pending REP only converts to available REP when the final milestone is complete for the grant.The issue is that applicants cannot fully engage with the ecosystem (using REP) until their grants are entirely complete, which can take extended periods of time for larger grants. This decreases engagement from new VAs and does not optimize the timely distribution of REP.
- VAs voting on grants “stake” their REP towards a formal vote. If this formal vote passes, they receive a pro-rata portion of the total minted pending REP from the “policing ratio” as calculated by the number of REP points they voted with compared to the total REP points of all VAs voting. The VA then immediately receives the REP staked to the vote back when the vote concludes, along with gaining a line item in the minted pending column of their REP chart as a portion of the grant’s REP generated by the “policing ratio.”This causes two issues.
- Grant applicants cannot fully engage with the ecosystem (using REP) until their grants are entirely complete, which can take extended periods of time for larger grants. This decreases engagement from new VAs and does not optimize the timely distribution of REP. This is a symptom of departures from the original MVPR system that is described in the cited works of #18; in the cited system, evidence is to be submitted for the completed work alongside the request for payment, thereby eliminating this 'lag time'. However, it is inherently impractical to asking individuals and companies to shoulder the entire burden of development cost. The costs surrounding software development are simply too great, necessitating the departure.
- Over time, VAs with larger REP pools as they vote on high-value grants. VAs with large REP pools can vote the maximum allowed - to reserve a large portion of the minted pending REP - as compared to those with smaller REP pools. This can create a widening gap between the REP earned by new VAs versus older VAs based solely on the relatively passive activity of voting. Cycling large amounts of reputation on every vote gives established VAs a large advantage. This is a departure in spirit from the cited works in #18. A core tenet of the MVPR system is that voting associates must literally stake their reputation in proportion to the strength of their opinion on the subject at hand. At current, this is functionally not done as the REP is returned before the result of the subject at hand is known.We resolve a solution to both issues.

**Comment by ledgerleapllc** [comment]
jira 429

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/commit/090dc624a6ea0d72f7284e06f81a7fef40362a8a

**Comment by opticalresolution** [comment]
https://github.com/ledgerleapllc/devxdao-backend/issues/113

**Comment by ledgerleapllc** [comment]
Commit https://github.com/ledgerleapllc/devxdao-backend/commit/090dc624a6ea0d72f7284e06f81a7fef40362a8a
PR https://github.com/ledgerleapllc/devxdao-backend/pull/117
PR https://github.com/ledgerleapllc/devxdao-backend/pull/83
PR https://github.com/ledgerleapllc/devxdao-backend/pull/80
PR https://github.com/ledgerleapllc/devxdao-backend/pull/79
PR https://github.com/ledgerleapllc/devxdao-backend/pull/78

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/pull/125
